# Generated by Django 2.2 on 2019-05-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Part number')),
                ('number', models.IntegerField()),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('count', models.IntegerField(null=True, verbose_name='Количество на складе')),
                ('date_register', models.DateTimeField(null=True, verbose_name='date_create')),
                ('analog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Component')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Box')),
            ],
        ),
        migrations.CreateModel(
            name='GroupComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип упаковки компонента')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date_create')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.Position')),
            ],
        ),
        migrations.CreateModel(
            name='UnPuking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('time', models.DateTimeField(verbose_name='date_create')),
                ('status', models.BooleanField(blank=True, verbose_name='Что то не так')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.User')),
            ],
        ),
        migrations.CreateModel(
            name='TrashComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date_create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.User')),
                ('wrute_off_ditail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Component')),
                ('wrute_off_group_ditail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.GroupComponents')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, verbose_name='quantity')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.Component')),
            ],
        ),
        migrations.AddField(
            model_name='groupcomponents',
            name='components',
            field=models.ManyToManyField(to='comp_control.QuantityComponent'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='serial_number')),
                ('assembler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.User')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.GroupComponents', verbose_name='Прибор')),
            ],
        ),
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='count_time')),
                ('status', models.BooleanField(verbose_name=('Ok', 'Ошибка'))),
                ('count', models.IntegerField()),
                ('unpuking', models.ManyToManyField(to='comp_control.UnPuking')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='counting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Counting', verbose_name='Дата последнего поступлениея на склад'),
        ),
        migrations.AddField(
            model_name='component',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Package'),
        ),
        migrations.AddField(
            model_name='component',
            name='type_ditail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Type', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='component',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.Unit', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp_control.Storage'),
        ),
    ]
