# Generated by Django 2.2.1 on 2019-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0002_auto_20190610_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отнять'),
        ),
        migrations.AlterField(
            model_name='component',
            name='plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Добавить'),
        ),
    ]
