# Generated by Django 2.2.1 on 2019-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0003_auto_20190610_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='minus',
        ),
        migrations.RemoveField(
            model_name='component',
            name='plus',
        ),
        migrations.AddField(
            model_name='component',
            name='action',
            field=models.IntegerField(choices=[(0, 'Minus'), (1, 'Plus')], null=True),
        ),
    ]
