# Generated by Django 2.2 on 2019-05-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0003_auto_20190504_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitycomponent',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
    ]
