# Generated by Django 2.2.1 on 2019-06-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0004_auto_20190610_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
