# Generated by Django 2.2 on 2019-05-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0004_auto_20190504_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashcomponents',
            old_name='wrute_off_ditail',
            new_name='write_off_ditail',
        ),
        migrations.RenameField(
            model_name='trashcomponents',
            old_name='wrute_off_group_ditail',
            new_name='write_off_group_ditail',
        ),
    ]
