# Generated by Django 2.2 on 2019-05-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0005_auto_20190505_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcomponents',
            name='count_detail',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество списанных деталей'),
        ),
        migrations.AddField(
            model_name='trashcomponents',
            name='count_group_detail',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество списанных детлей в группе'),
        ),
    ]
