# Generated by Django 2.2 on 2019-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0006_auto_20190505_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcomponents',
            name='count_release',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество в производство'),
        ),
    ]
