# Generated by Django 2.2 on 2019-05-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0007_groupcomponents_count_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='count_group_detail',
        ),
    ]
