# Generated by Django 2.2 on 2019-05-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0008_remove_trashcomponents_count_group_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcomponents',
            old_name='count_release',
            new_name='plan',
        ),
    ]
