# Generated by Django 2.2.1 on 2019-06-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0008_auto_20190610_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя позиции'),
        ),
    ]
