# Generated by Django 2.2 on 2019-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0009_auto_20190506_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcomponents',
            name='count_group_detail',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество списанных детлей в группе'),
        ),
    ]
