# Generated by Django 2.2 on 2019-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0010_trashcomponents_count_group_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='count_group_detail',
            field=models.IntegerField(blank=True, verbose_name='количество плат'),
        ),
    ]
