# Generated by Django 2.2 on 2019-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0011_auto_20190510_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='count_group_detail',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество плат'),
        ),
    ]
