# Generated by Django 2.2.1 on 2019-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0012_auto_20190510_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_create'),
        ),
        migrations.RemoveField(
            model_name='trashcomponents',
            name='write_off_ditail',
        ),
        migrations.AddField(
            model_name='trashcomponents',
            name='write_off_ditail',
            field=models.ManyToManyField(blank=True, to='comp_control.Component'),
        ),
    ]
