# Generated by Django 2.2.1 on 2019-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0013_auto_20190602_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='write_off_ditail',
            field=models.ManyToManyField(blank=True, to='comp_control.QuantityComponent'),
        ),
    ]
