# Generated by Django 2.2.1 on 2019-06-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0014_auto_20190602_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='count_detail',
        ),
    ]
