# Generated by Django 2.2.1 on 2019-06-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0015_remove_trashcomponents_count_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='write_off_ditail',
        ),
        migrations.AddField(
            model_name='trashcomponents',
            name='write_of_component',
            field=models.ManyToManyField(blank=True, to='comp_control.Component'),
        ),
    ]
