# Generated by Django 2.2.1 on 2019-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0016_auto_20190605_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='write_of_component',
        ),
        migrations.AddField(
            model_name='trashcomponents',
            name='write_off_ditail_in_bom',
            field=models.ManyToManyField(blank=True, to='comp_control.QuantityComponent'),
        ),
    ]
