# Generated by Django 2.2.1 on 2019-06-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0017_auto_20190605_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='write_off_ditail_in_bom',
            field=models.ManyToManyField(blank=True, null=True, to='comp_control.QuantityComponent'),
        ),
    ]
