# Generated by Django 2.2.1 on 2019-06-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0019_auto_20190605_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='write_off_group_ditail',
        ),
    ]
