# Generated by Django 2.2.1 on 2019-06-06 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0021_trashcomponents_write_off_group_ditail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcomponents',
            name='write_off_group_ditail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp_control.GroupComponents'),
        ),
    ]
