# Generated by Django 2.2.1 on 2019-06-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0023_auto_20190606_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashcomponents',
            name='write_off_ditail_in_bom',
        ),
    ]
