# Generated by Django 2.2.1 on 2019-06-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp_control', '0024_remove_trashcomponents_write_off_ditail_in_bom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcomponents',
            name='plan',
        ),
    ]
